### ISSUE TITLE
Week 1 Scrum Update

### ISSUE THREAD

**Issue by mxg895** [mxg895/next-story#4]
What did you work on this past iteration (2 weeks)?
What were any major issues/challenges you ran into?
What do you plan to work on for this coming iteration (2 weeks)?

**Comment by warrenkwchan** [comment]
What did you work on this past iteration (2 weeks)?
I have been collaborating with my lovely teammates to come up with project ideas and put them on our github Readme page.

What were any major issues/challenges you ran into?
The issues may be trying to decide what resources (APIs for recommendation system, books, and movie retrieval) we can leverage to meet our application requirements.

What do you plan to work on for this coming iteration (2 weeks)?
I plan to work on components next and we will have a group discussion this coming Monday to allocate tasks for each member.

**Comment by mxg895** [comment]
**What did you work on this past iteration?**
I worked with our group to brainstorm ideas about the project, set up the project repo (and added branch protection), connected the Github-Slack integration, and made a PR for partially formatting the README.

**What were any major issues/challenges you ran into?**
We had some issue with trying to decide on the final topic for the project from all the project ideas that we came up with. We ended up listing out what can be done with each individual idea in more detail before making a decision collectively. I had some issues with learning to use Figma to add components. This is a tool that I have never used before.

**What do you plan to work on for this coming iteration?**
Setting up the React app, doing some research into the UI/theme packages for React, tsconfig (as we are planning on using TS & TSX) and lint rules that we can set up to standardize our code format, as well as building at least 1-2 components out of the list of components that our group decide to build.

**Comment by davidzc01** [comment]
I worked on deciding project topic, draw project prototype, and review pull request on readme.

The major challenge would be deciding the project topic and planning project requirements

I plan to working on components and other works based on our discussion on Monday

**Comment by MayKikuchi** [comment]
What did you work on this past iteration?
 - As a team we decided on what our project would and our project requirements.

What were any major issues/challenges you ran into?
 - Figma was a little tricky to use at first when making the prototypes.

What do you plan to work on for this coming iteration?
 - With the team, figure out what styling library to use and figure out the main components and pages, and select a movie and book database api
 - Individually, start building some components, and maybe hook up a database api

**Comment by dustxd** [comment]
Please post your CSIDs in your scrum reports next time :3
