### ISSUE TITLE
BUGS!

### ISSUE THREAD

**Issue by MayKikuchi** [mxg895/next-story#98]
A list of bugs that need fixing:
Please put your name beside what you're working on so there's no overlap
Might also be nice to un-bold once done

- There are a lot of pending requests in the home page and I think that gives rise to some issues, including subsequent page navigation being unable to load until refreshed - seems ok on the current heroku deployed version so idk what's happening here (May - DONE):
![pending rec bug](https://user-images.githubusercontent.com/48613270/88751908-7cfda880-d10d-11ea-8f25-70c86449d8ba.png)
![home to media page unmount bug](https://user-images.githubusercontent.com/48613270/88751914-80912f80-d10d-11ea-9ebd-c2caaa55d00b.png)

- clicking on some book-specific genres freezes the app (will navigate to an empty single search result page and freeze)  (May - DONE)
![book genre click freezes app](https://user-images.githubusercontent.com/48613270/88752061-d5cd4100-d10d-11ea-82ff-33d755654613.png)

- can't add favorite genres yet (May - DONE)

- blurbs and genres in the media modal and the media page don't match (May ...not sure I want to change this actually, might be nice to have a 'condensed' version on the modal) (Warren - done - no further work needed because the inconsistency indeed comes from google book api)
![blurbs don't match bug](https://user-images.githubusercontent.com/48613270/88758672-d79f0080-d11d-11ea-8efe-2f4d65062c05.png)

- let's clean up all the yellow warnings in the developer console, and all the todos and unnecessary console.logs before our final deployment (Warren - Done but new warning may come up after profile and explore page added)

- Page not found displays for some media pages where it shouldn't ... try clicking first found Harry Potter (May - oops - DONE)

- searching by genre tags for books is a general search and not category specific (May - I don't really think this can be fixed, seems broken on the Google Api side)

- clicking on a director takes user to book filter instead of movie filter (May -DONE)

- Explore page bugs (May - DONE):

1. the text at the bottom still says 'Loading more results...' even when there are no more results to load (sometimes)
2. Clicking on **both** books and movies checkboxes, then searching returns no results (sometimes)
3. changing the type and searching again after getting no results sometimes leads to getting no results, even when there should be with the new media type being searched for

- _Some_ devices give a Error 400 redirect_uri_mismatch error when trying to sign in or login with google (May - DONE ...probably)
possible fixes:
1. clear cache
2. make sure that the url is going to https://next-story436i.herokuapp.com, and specify typing in the https part

- the Top and bottoms Media Modal bars get covered up by the top and bottom browser bars in mobile (an actual phone chrome browser, not the simulator on web) (May - DONE)

- sometimes the mock covers are briefly shown, let's get rid of the mock covers and just have grey rectangles or null instead (May - DONE)

- logging in with google before signing up leads to nothing happening (May - DONE)

**Comment by warrenkwchan** [comment]
"A cookie associated with a cross-site resource at https://accounts.google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with..." is just the chrome advertisement not from our code. will continue solving warnings coming from our projects.

"Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure image '<URL>'. This content should also be served over HTTPS." should also be fixed now

**Comment by MayKikuchi** [comment]
@warrenkwchan just fyi, but if you click a tag button to take you to the search results page, you might get a bunch of 404 errors... those are probably because the app is trying to fetch 'book-000', etc dummy id types from the third party apis and are unable to find them (should be verifiable by checking the uri they're being fetched from in the network tab). They should go away when the dummy data is cleared out of the mongodb database

**Comment by warrenkwchan** [comment]
Yes, I know. I use deployed app as the source of truth

**Comment by MayKikuchi** [comment]
the deployed app should also still have dummy data? (cause it's connected to my mongodb database) Or are you using your own deploy? not important though haha 🤷

**Comment by warrenkwchan** [comment]
the error is indeed there. wasn't clicking the right button to trigger that

**Comment by MayKikuchi** [comment]
for the issue where the blurbs and genres in the media modal and the media page don't match, I was thinking it might be good to just leave this as-is. I get why it's happening, but it might be nice to have a shortened version in the modal, what does everyone else think?
